### ISSUE TITLE
Add 'repository' attribute for tasks

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/ossboard#10]
I think this attribute will be useful for searching tasks.

For this we need: 
- [ ] create repository column;
- [ ] add input field to new task form;
- [ ] update export logic for getting repository value;
- [ ] repository field should be required;
- [ ] update admin application for new attribute (display in `tasks#index`, `tasks#show` and update update form);

**Comment by vladimirich** [comment]
It's ok if I'll get this issue, but start working on it at New Year holidays?

**Comment by moofkit** [comment]
@nsklkn sorry man. I had some free time for oss and this issue seems suitable for me

**Comment by davydovanton** [comment]
@moofkit sorry, but I want to see repository name column for future grouping and searching by this field. That's why `repository_url` unnecessary for us now 😞

**Comment by davydovanton** [comment]
and also I think that we need to use `optional` field for this attribute

**Comment by moofkit** [comment]
@davydovanton So, we need `optional` `repository_name` attribute. Is it correct?

**Comment by moofkit** [comment]
According gh [api documentation](https://developer.github.com/v3/repos/#response-3) there are 2 attributes connected with name: `name` and `full_name`. Which is need to use?
Also if user input repo name by himself, need we some normalization or format validation?

**Comment by davydovanton** [comment]
@moofkit yep, I want to see `repository_name`. We can use it from github link or we can ask the user to enter it

**Comment by davydovanton** [comment]
closed by #25
