### ISSUE TITLE
Add new field time_estimate

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/ossboard#29]
It will be helpful for understanding how many time you need to spend on task

For this we need:

- create time_estimate column;
- create the hash of values ('few days', 'more than a week', 'more than two weeks', 'more than month');
- add 'select' field to new task form;
- 'few days' options should be default;
- update admin application for the new attribute (display in tasks#index, tasks#show and update form);

**Comment by mgrachev** [comment]
I will take it.

**Comment by davydovanton** [comment]
@mgrachev 👍
