### ISSUE TITLE
Error: md body is missing

### ISSUE THREAD

**Issue by KELiON** [davydovanton/ossboard#37]
I'm trying to add a task from issue. Steps:

1. Click "export from";
1. Paste link to github issue;
1. Update task body and change some other fields;
1. Click "Preview"
1. Click "Create" 
1. Error "md body is missing" shown, but body was not empty

### Gif
![](http://g.recordit.co/LggYAHwDjF.gif)

**Comment by davydovanton** [comment]
thanks for bug request 👍
