### ISSUE TITLE
500 error shown for properly filled task form

### ISSUE THREAD

**Issue by KELiON** [davydovanton/ossboard#38]
After error from https://github.com/davydovanton/ossboard/issues/37 I've changed task body and clicked "create" button, but `500 – Internal server error` was shown. Also, after refreshing page I was not logged in.

### Gif
![](http://g.recordit.co/MUbDVfEgSS.gif)

**Comment by davydovanton** [comment]
I fixed. Form for tasks#update didn't generate csrf token. That's why you had the error.
Thanks for bug report 👍
