### ISSUE TITLE
Fix body text area width after preview

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/ossboard#41]
1. go to `/tasks/new`
2. select `preview` button
3. select `write` button

**Comment by charlie-wasp** [comment]
@davydovanton what exactly is wrong with that? I can't see any problems

**Comment by r00takaspin** [comment]
@davydovanton 
![image](https://cloud.githubusercontent.com/assets/2390121/22000491/0c783746-dc48-11e6-86c0-f5476b46d68d.png)

there is javascript error in console and there is no auto formatting when selecting language. Is it  described problem?

**Comment by davydovanton** [comment]
@r00takaspin hey, you choose task language. It's mean that language code in task body and task language can be different. I mean other problem. You can see it in gif:
![sbyheo2tp0](https://cloud.githubusercontent.com/assets/1147484/22000868/b31ba9d4-dc52-11e6-9f82-37b9f6097096.gif)

**Comment by FChaack** [comment]
I made some tests in different browsers and currently, there is no bug with text area width.

**Comment by davydovanton** [comment]
Thanks for help @FChaack 👍
