### ISSUE TITLE
Export from gitlab

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/ossboard#42]
We need to find easily solution how to export issues from gitlab

**Comment by Bugagazavr** [comment]
Most pain is a gitlab API

For example issues in gitlab has two IDs, global id - primary key, and internal autoincreament, internal id for project

When user pass url to issue on gitlab, url contains internal id for issue, but api working only with global IDs. ( documentation lies )

Documenation:
https://docs.gitlab.com/ee/api/issues.html#single-issue

Screenshots:
![screen shot 2017-01-14 at 18 06 53](https://cloud.githubusercontent.com/assets/683590/21956217/b5d370fa-da84-11e6-87c1-927cb81efb7b.png)
![screen shot 2017-01-14 at 18 06 38](https://cloud.githubusercontent.com/assets/683590/21956218/b5d44a66-da84-11e6-984d-0cdc2e5a96da.png)

**Comment by thepry** [comment]
To access the https://gitlab.com/gitlab-org/gitlab-ce/issues/27371 we need:
1. Replace '/` between organization and project with `%2F`
2. Get the scope-unique id (iid) `27371` and use it as a parameter for a query.
3. As a result we will get an array containing 1 (if id is correct and we have access) or 0 elements.

```
curl --header "PRIVATE-TOKEN: YOUR_GITLAB_TOKEN" https://gitlab.com/api/v3/projects/gitlab-org%2Fgitlab-ce/issues/?iid=27371

[{"id":4090096,"iid":27371,"project_id":13083,"title":"Set protected branches...
```

So it's quite easy if we do it on a server and have a valid gitlab api token.

**Comment by thepry** [comment]
And this one. I can work on the implementation

**Comment by davydovanton** [comment]
@thepry cool, I can create gitlab token for this 👍

**Comment by davydovanton** [comment]
@thepry thanks for work 👍
