### ISSUE TITLE
Cannot get webpack dev server manifest 

### ISSUE THREAD

**Issue by charlie-wasp** [davydovanton/ossboard#46]
Hi,

It seems that hanami-webpack gem was updated recently, now on the project launch I receive an error `JSON::ParserError: 743: unexpected token at 'Cannot GET /webpack_manifest.json '` in browser.

I guess, guys renamed manifest file default and added env variable for overriding (check out this commit https://github.com/samuelsimoes/hanami-webpack/commit/1019f8efc217c9ae7290e220bf2c9e05ddd603ae)

I fixed it locally, changing manifest name in `webpack.config.js` to `webpack_manifest.json` from simply `manifest.json`

If this problem exists not only for me, maybe we should fix the default or add corresponding environment variable in .env files?

**Comment by davydovanton** [comment]
Hey, thanks for a report. I updated my gems, and yes, I have this problem too. I think it will better to rename manifest file to `webpack_manifest.json` in webpack config
