### ISSUE TITLE
Post approved tasks in twitter account

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/ossboard#54]
We need to update sidekiq worker to post all approved tasks in our twitter account (http://twitter.com/oss_board). I think `title #ossboard link` will goof format for tweets

**Comment by thepry** [comment]
I can do it

**Comment by davydovanton** [comment]
Fixed, thanks 👍

**Comment by davydovanton** [comment]
I checked this code on production and all works correct. Good job 👍 
https://twitter.com/oss_board/status/826817959993683972
