### ISSUE TITLE
Add 'complexity' attribute for tasks

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/ossboard#9]
I think this attribute will be useful for searching tasks.

For this we need: 
- [ ] create complexity column with default value `easy`;
- [ ] add select field to new task form (default `easy` too);
- [ ] complexity field should be required;
- [ ] update admin application for new attribute (display in `tasks#show` and update update form);

**Comment by charlie-wasp** [comment]
I can take it for the holidays, is it ok?

**Comment by davydovanton** [comment]
yep 👍

**Comment by charlie-wasp** [comment]
I opened PR #24 for this task
